name: Build and deploy Python app to Azure Web App - helmetviolation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create virtual environment, upgrade pip and ensure clean Pillow
        shell: bash
        run: |
          python -m venv antenv
          source antenv/bin/activate

          # upgrade pip and build tooling
          python -m pip install --upgrade pip setuptools wheel

          # ensure any previously cached Pillow is removed
          python -m pip uninstall -y pillow Pillow || true
          pip cache purge || true

          # Preinstall a single Pillow version to avoid dependency resolution conflict.
          # Recommended: keep Pillow==10.0.1 for Azure compatibility.
          pip install "Pillow==10.0.1"

      - name: Install project dependencies (inside venv)
        shell: bash
        run: |
          source antenv/bin/activate
          # Now install the rest of the requirements
          pip install -r requirements.txt

      # Upload artifact for deployment jobs
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EA598CA0E35942479A3BF3761F792817 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F397D0C267E74B078379784B5EA9015E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7C5F0A9C88AA4466A4286EE4CF13B5A9 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'helmetviolation'
          slot-name: 'Production'
